### ISSUE TITLE
Don't show users who are not pending or friends on the friends list

### ISSUE THREAD

**Issue by HugoKawamata** [MaxwellBo/suq#70]
Unless they have been searched for specifically - this is a big one that we should have before beta release

**Comment by charltongroves** [comment]
yeah good idea.
Adding to this, we should make it so that your facebook friends show up without having to search for them

**Comment by HugoKawamata** [comment]
That's also good but not quite as important. Users care about privacy, especially when they're uploading personal information and ESPECIALLY onto an app they haven't ever heard of before.

**Comment by HugoKawamata** [comment]
Completed
